# Generated by Django 5.1.4 on 2025-01-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
