# Generated by Django 5.1.4 on 2025-01-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_new_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='point',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='new',
            name='seminary',
            field=models.BooleanField(default=False),
        ),
    ]
